enum class BlockRenderLayer : unsigned int
{
    RENDERLAYER_DOUBLE_SIDED,
    RENDERLAYER_RAY_TRACED_WATER,
    RENDERLAYER_BLEND,
    RENDERLAYER_OPAQUE,
    RENDERLAYER_OPTIONAL_ALPHATEST,
    RENDERLAYER_ALPHATEST,
    RENDERLAYER_SEASONS_OPAQUE,
    RENDERLAYER_SEASONS_OPTIONAL_ALPHATEST,
    RENDERLAYER_ALPHATEST_SINGLE_SIDE,
    RENDERLAYER_ENDPORTAL,
    RENDERLAYER_BARRIER,
    RENDERLAYER_LIGHT,
    RENDERLAYER_STRUCTURE_VOID,
    _RENDERLAYER_COUNT
}
