
class ClientInstance : public IClientInstance, public Core::StorageAreaStateListener, public GameCallbacks, public PlayerListener, public std::enable_shared_from_this<ClientInstance> { /* Size=0x998 */
  /* 0x0000: fields for IClientInstance */
  /* 0x0008: fields for Core::StorageAreaStateListener */
  /* 0x0070: fields for GameCallbacks */
  /* 0x0078: fields for PlayerListener */
  /* 0x0080: fields for std::enable_shared_from_this<ClientInstance> */
  /* 0x0090 */ ClientInstanceState mClientState;
  /* 0x0098 */ IMinecraftApp& mApp;
  /* 0x00a0 */ LevelListener& mLevelListener;
  /* 0x00a8 */ IMinecraftGame& mMinecraftGame;
  /* 0x00b0 */ std::unique_ptr<Minecraft,std::default_delete<Minecraft> > mMinecraft;
  /* 0x00b8 */ std::unique_ptr<AbstractClientInstanceTestInterface,std::default_delete<AbstractClientInstanceTestInterface> > mTestClientInstanceInterface;
  /* 0x00c0 */ bool mIsFullVanillaPackOnStack;
  /* 0x00c8 */ std::unique_ptr<LevelRenderer,std::default_delete<LevelRenderer> > mLevelRenderer;
  /* 0x00d0 */ std::unique_ptr<LightTexture,std::default_delete<LightTexture> > mLightTexture;
  /* 0x00d8 */ std::unique_ptr<ImGuiClientModuleMan,std::default_delete<ImGuiClientModuleMan> > mImguiModuleMan;
  /* 0x00e0 */ std::unique_ptr<LoopbackPacketSender,std::default_delete<LoopbackPacketSender> > mPacketSender;
  /* 0x00e8 */ std::unique_ptr<HolographicPlatform,std::default_delete<HolographicPlatform> > mHoloInput;
  /* 0x00f0 */ std::unique_ptr<VoiceSystem,std::default_delete<VoiceSystem> > mVoiceSystem;
  /* 0x00f8 */ std::unique_ptr<MoveInputHandler,std::default_delete<MoveInputHandler> > mClientMoveInputHandler;
  /* 0x0100 */ std::unique_ptr<ClientInputHandler,std::default_delete<ClientInputHandler> > mClientInputHandler;
  /* 0x0108 */ std::unique_ptr<MinecraftKeyboardManager,std::default_delete<MinecraftKeyboardManager> > mKeyboardManager;
  /* 0x0110 */ std::unique_ptr<HitDetectSystem,std::default_delete<HitDetectSystem> > mHitDetectSystem;
  /* 0x0118 */ std::shared_ptr<UserAuthentication> mUserAuthentication;
  /* 0x0128 */ std::unique_ptr<SceneFactory,std::default_delete<SceneFactory> > mSceneFactory;
  /* 0x0130 */ std::unique_ptr<CachedScenes,std::default_delete<CachedScenes> > mCachesScenes;
  /* 0x0138 */ std::unique_ptr<CameraManager,std::default_delete<CameraManager> > mCameraManager;
  /* 0x0140 */ Actor* mCameraEntity;
  /* 0x0148 */ Actor* mCameraTargetEntity;
  /* 0x0150 */ LocalPlayer* mPlayer;
  /* 0x0158 */ std::unique_ptr<BuildActionIntention,std::default_delete<BuildActionIntention> > mInProgressBai;
  /* 0x0160 */ float mHoloviewerScale;
  /* 0x0164 */ float mRealityModeFrameFactor;
  /* 0x0168 */ bool mRealityModeToggleTriggered;
  /* 0x016c */ ClientPlayMode mPlayMode;
  /* 0x0170 */ bool mTickedLastFrame;
  /* 0x0171 */ std::atomic<bool> mOpenControllerDisconnectScreen;
  /* 0x0172 */ std::atomic<bool> mHandlingControllerDisconnect;
  /* 0x0173 */ std::atomic<bool> mConnectGamepadScreenActive;
  /* 0x0174 */ PlayScreenDefaultTab mDefaultPlayscreenTab;
  /* 0x0178 */ bool mIsInUpdate;
  /* 0x0179 */ bool mLivingRoomCredits;
  /* 0x0180 */ std::function<void __cdecl(void)> mCreditsCallback;
  /* 0x01c0 */ std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > > mNoBlockBreakUntil;
  /* 0x01c8 */ bool mNewDictationString;
  /* 0x01d0 */ std::basic_string<char,std::char_traits<char>,std::allocator<char> > mDictation;
  /* 0x01f0 */ mce::ViewportInfo mViewportInfo;
  /* 0x0208 */ ClientInstance::ClientRenderResources mClientRenderResources;
  /* 0x0258 */ mce::Texture* mLevelTexture;
  /* 0x0260 */ mce::Camera mCamera;
  /* 0x0430 */ ShaderColor mShaderColor;
  /* 0x0444 */ ShaderColor mDarkShaderColor;
  /* 0x0458 */ Vec3 mLastPointerLocation;
  /* 0x0468 */ std::unique_ptr<SceneStack,std::default_delete<SceneStack> > mSceneStack;
  /* 0x0470 */ std::unique_ptr<hbui::Router,std::default_delete<hbui::Router> > mUIRouter;
  /* 0x0478 */ std::unique_ptr<ContentCatalogService,std::default_delete<ContentCatalogService> > mServerService;
  /* 0x0480 */ std::unique_ptr<UIProfanityContext,std::default_delete<UIProfanityContext> > mUIProfanityContext;
  /* 0x0488 */ std::shared_ptr<TextToSpeechClient> mTextToSpeechClient;
  /* 0x0498 */ std::shared_ptr<TTSEventManager> mTTSEventManager;
  /* 0x04a8 */ std::unique_ptr<TaskGroup,std::default_delete<TaskGroup> > mTaskGroup;
  /* 0x04b0 */ std::unique_ptr<BlockTessellator,std::default_delete<BlockTessellator> > mBlockTessellator;
  /* 0x04b8 */ std::unique_ptr<BlockActorRenderDispatcher,std::default_delete<BlockActorRenderDispatcher> > mBlockEntityRenderDispatcher;
  /* 0x04c0 */ std::shared_ptr<ActorRenderDispatcher> mActorRenderDispatcher;
  /* 0x04d0 */ std::unique_ptr<ActorBlockRenderer,std::default_delete<ActorBlockRenderer> > mEntityBlockRenderer;
  /* 0x04d8 */ std::unique_ptr<ItemInHandRenderer,std::default_delete<ItemInHandRenderer> > mItemInHandRenderer;
  /* 0x04e0 */ std::unique_ptr<ItemRenderer,std::default_delete<ItemRenderer> > mItemRenderer;
  /* 0x04e8 */ std::unique_ptr<GuiData,std::default_delete<GuiData> > mGuiData;
  /* 0x04f0 */ std::unique_ptr<GuidedFlowManager,std::default_delete<GuidedFlowManager> > mGuidedFlowManager;
  /* 0x04f8 */ std::unique_ptr<MobEffectsLayout,std::default_delete<MobEffectsLayout> > mMobEffectsLayout;
  /* 0x0500 */ std::unique_ptr<ToastManager,std::default_delete<ToastManager> > mToastManager;
  /* 0x0508 */ const unsigned char mClientSubId;
  /* 0x0510 */ std::unique_ptr<SkinRepositoryClientInterface,std::default_delete<SkinRepositoryClientInterface> > mSkinRepositoryClientInterface;
  /* 0x0518 */ std::shared_ptr<persona::PersonaPieceCollectionModel> mPersonaPieceCollectionModel;
  /* 0x0528 */ ClientHMDState mHMDState;
  /* 0x07a8 */ std::unique_ptr<FogDefinitionRegistry,std::default_delete<FogDefinitionRegistry> > mFogDefinitionRegistry;
  /* 0x07b0 */ std::unique_ptr<FogManager,std::default_delete<FogManager> > mFogManager;
  /* 0x07b8 */ bool mIsSceneStackChanging;
  /* 0x07c0 */ std::unique_ptr<ScreenLoadTimeTracker,std::default_delete<ScreenLoadTimeTracker> > mScreenLoadTimeTracker;
  /* 0x07c8 */ bool mHasSwitchedScreen;
  /* 0x07c9 */ bool mShouldLeaveGame;
  /* 0x07ca */ bool mPreparingToLeaveGame;
  /* 0x07cb */ bool mIsLeavingGame;
  /* 0x07cc */ bool mSyncLeaveGame;
  /* 0x07cd */ bool mDestroyingGame;
  /* 0x07ce */ bool mShuttingDown;
  /* 0x07cf */ bool mUsingTripodNow;
  /* 0x07d0 */ std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > > mServerConnectionTime;
  /* 0x07d8 */ int32_t mServerPingTime;
  /* 0x07e0 */ std::deque<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > mSentMessageHistory;
  /* 0x0808 */ std::deque<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > mDevConsoleMessageHistory;
  /* 0x0830 */ std::shared_ptr<IGameConnectionListener> mGameConnectionListener;
  /* 0x0840 */ std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,enum BehaviorStatus)> mBehaviorCommandStatusCallback;
  /* 0x0880 */ std::unique_ptr<UIEventCoordinator,std::default_delete<UIEventCoordinator> > mUIEventCoordinator;
  /* 0x0888 */ std::unique_ptr<ClientHitDetectCoordinator,std::default_delete<ClientHitDetectCoordinator> > mHitEventCoordinator;
  /* 0x0890 */ std::unordered_map<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,int,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::pair<std::basic_string<char,std::char_traits<char>,std::allocator<char> > const ,int> > > mProfanityExactMap;
  /* 0x08d0 */ std::unordered_set<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::hash<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::equal_to<std::basic_string<char,std::char_traits<char>,std::allocator<char> > >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > > mProfanityContainsSet;
  /* 0x0910 */ std::unique_ptr<EducationOptions,std::default_delete<EducationOptions> > mEducationOptions;
  /* 0x0918 */ glm::vec<2,float,0> mPrevCursorPos;
  /* 0x0920 */ glm::vec<2,float,0> mCurrentCursorPos;
  /* 0x0928 */ float mCursorPosAlpha;
  /* 0x0930 */ LatencyGraphDisplay* mLatencyGraphDisplay;
  /* 0x0938 */ std::unique_ptr<GameModuleClient,std::default_delete<GameModuleClient> > mGameModule;
  /* 0x0940 */ gsl::not_null<Bedrock::NonOwnerPointer<ClientInstanceEventCoordinator> > mEventCoordinator;
  /* 0x0950 */ std::unique_ptr<MinecraftClientScriptEngine,std::default_delete<MinecraftClientScriptEngine> > mScriptEngine;
  /* 0x0958 */ std::unique_ptr<PlayerCapabilities::IClientController,std::default_delete<PlayerCapabilities::IClientController> > mClientCapabilities;
  /* 0x0960 */ std::unique_ptr<hbui::SceneProvider,std::default_delete<hbui::SceneProvider> > mSceneProvider;
  /* 0x0968 */ hbui::Telemetry mHBUITelemetry;
  /* 0x0980 */ std::shared_ptr<ClientRequirementVerifier> mClientRequirementVerifier;
  /* 0x0990 */ std::unique_ptr<DebugInfoPacketHandler,std::default_delete<DebugInfoPacketHandler> > mDebugInfoPacketHandler;
  
  ClientInstance(IMinecraftGame&, IMinecraftApp&, LevelListener&, unsigned char, const gsl::not_null<Bedrock::NonOwnerPointer<ClientInstanceEventCoordinator> >&, LatencyGraphDisplay*);
  virtual ~ClientInstance();
  virtual void onInitMinecraftGame();
  virtual void onDestroyMinecraftGame();
  virtual void init(Core::FilePathManager*, NetworkHandler&, Timer&, Timer&, const gsl::not_null<Bedrock::NonOwnerPointer<Social::IUserManager> >&, int32_t, IGameModuleApp&);
  virtual void initSceneFactory(hbui::ILibrary*, std::unique_ptr<SceneFactory,std::default_delete<SceneFactory> >, std::unique_ptr<hbui::SceneProvider,std::default_delete<hbui::SceneProvider> >);
  virtual void setUiRouter(std::unique_ptr<hbui::Router,std::default_delete<hbui::Router> >);
  virtual void initGraphics();
  virtual void stop();
  virtual void teardown();
  virtual void preShutDown();
  virtual void requestLeaveGame(bool, bool);
  virtual void stopPlayScreen();
  virtual bool isLeaveGameDone() const;
  virtual void setupPlayScreenForLeaveGame();
  virtual void resetPrimaryClient();
  virtual void resetGameSession();
  virtual void tick();
  virtual void frameUpdate(FrameUpdateContext&);
  virtual bool update(bool);
  virtual void endFrame();
  virtual void startSubClientLateJoin(bool, std::unique_ptr<GameModuleClient,std::default_delete<GameModuleClient> >);
  virtual void setupClientGame(std::function<void __cdecl(enum ClientGameSetupResult)>&, bool, std::unique_ptr<GameModuleClient,std::default_delete<GameModuleClient> >);
  virtual BlockSource& getRegion();
  virtual const LocalPlayer* getLocalPlayer() const;
  virtual LocalPlayer* getLocalPlayer();
  virtual Actor* getCameraEntity() const;
  virtual void setCameraEntity(Actor*);
  virtual Actor* getCameraTargetEntity() const;
  virtual void setCameraTargetEntity(Actor*);
  virtual bool isLeavingGame() const;
  virtual bool isDestroyingGame() const;
  virtual bool isShuttingDown() const;
  virtual bool useLowFrequencyUIRender() const;
  virtual bool isSplitScreenActive() const;
  virtual bool isVRClient() const;
  virtual bool isARClient() const;
  virtual bool isARVRClient() const;
  virtual bool isHoloviewerMode() const;
  virtual bool isHoloscreenMode() const;
  virtual bool isLivingroomMode() const;
  virtual bool isExitingLevel() const;
  virtual bool isNotVLRMode() const;
  virtual bool isHoloRealityMode() const;
  virtual bool isRealityFullVRMode() const;
  virtual bool isInBedScreen() const;
  virtual bool isKeyboardEnabled() const;
  virtual bool isVRTransitioning() const;
  virtual bool hasCommands() const;
  virtual bool isScriptingEnabled() const;
  virtual float getHoloviewerScale() const;
  virtual int32_t getSplitScreenCount() const;
  virtual bool isStereoRendering() const;
  virtual bool isPlatformNX() const;
  virtual bool isLocalSplitscreenWith(const ActorUniqueID&) const;
  virtual bool isValidCrossPlatformSkin() const;
  virtual bool isSelectedSkinInitialized() const;
  virtual SplitScreenInfo getSplitScreenInfo() const;
  virtual int32_t getCurrentMaxGUIScaleIndex() const;
  virtual const float& getRealityModeFrameFactor() const;
  virtual void setRealityModeFrameFactor(const float&);
  virtual bool getRealityModeToggleTriggered() const;
  virtual void setRealityModeToggleTriggered(bool);
  virtual bool getHandlingControllerDisconnect();
  virtual void setOpenControllerDisconnectScreen(bool);
  virtual const ClientPlayMode& getClientPlayMode() const;
  virtual void setClientPlayMode(const ClientPlayMode&);
  virtual bool getLivingRoomForCredits() const;
  virtual void setLivingRoomForCredits(bool);
  virtual std::function<void __cdecl(void)> getCreditsCallback();
  virtual void setCreditsCallback(std::function<void __cdecl(void)>);
  virtual void setupTransitionForCredits(std::function<void __cdecl(void)>);
  virtual void refreshScreenSizeData();
  virtual void onScreenSizeChanged(int32_t, int32_t, float);
  virtual void onGuiScaleOffsetChanged();
  virtual void onSafeZoneChanged();
  virtual void quit(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual IMinecraftGame& getMinecraftGame() const;
  virtual IClientInstances& getClientInstances() const;
  virtual Automation::AutomationClient& getAutomationClient() const;
  virtual IMinecraftEventing& getEventing() const;
  virtual IConnectionEventing& getConnectionEventing() const;
  virtual FontHandle getFontHandle() const;
  virtual FontHandle getRuneFontHandle() const;
  virtual FontHandle getUnicodeFontHandle() const;
  virtual std::shared_ptr<GeometryGroup> getGeometryGroup() const;
  virtual Social::MultiplayerServiceManager& getMultiplayerServiceManager() const;
  virtual Level* getLocalServerLevel();
  virtual IResourcePackRepository& getResourcePackRepository() const;
  virtual ResourcePackManager& getResourcePackManager() const;
  virtual PackManifestFactory& getPackManifestFactory();
  virtual const IContentKeyProvider& getKeyProvider();
  virtual const PacksInfoData& getHostSpecifiedPacks() const;
  virtual std::shared_ptr<SkinRepository> getSkinRepository() const;
  virtual PersonaRepository& getPersonaRepository() const;
  virtual SkinRepositoryClientInterface& getSkinRepositoryClientInterface() const;
  virtual persona::PersonaPieceCollectionModel& getPersonaPieceCollectionModel();
  virtual std::shared_ptr<mce::TextureGroup> getTextureGroup() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<mce::TextureGroup> > getStoreCacheTextures() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<MinecraftGraphics> > getMinecraftGraphics() const;
  virtual UIRepository* getUIRepository() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<Social::IUserManager> > getUserManager() const;
  virtual bool wantToQuit() const;
  virtual bool isPrimaryLevelCrossPlatformMultiplayer() const;
  virtual bool isPrimaryLevelMultiplayer() const;
  virtual bool isAdhocEnabled() const;
  virtual void handleResizeScreen(int32_t);
  virtual const std::basic_string<char,std::char_traits<char>,std::allocator<char> > getTitleString(const EmulatedScreenSize&);
  virtual DebugInfoPacketHandler& getDebugInfoPacketHandler() const;
  virtual DebugInfoMessageDispatcher& getDebugInfoMessageDispatcher() const;
  virtual bool isMarketplaceDisabled() const;
  virtual void linkToOffer(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, bool, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void linkTo3PServerOffers(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void navigateToBrazeScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void navigateToStoreHomeScreen();
  virtual void navigateToCoinPurchaseScreen(int32_t, std::function<void __cdecl(bool)>);
  virtual void navigateToPurchaseOfferScreen(StoreCatalogItem&, StoreNavigationOrigin, const bool);
  virtual void navigateToStoreSeeAllByCreatorScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const bool);
  virtual void navigateToDressingRoomOfferScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void navigateToServersScreen(const bool);
  virtual void navigateToHowToPlayScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void tryPushLeaveGameScreen();
  virtual void tryStartDayOneExperience();
  virtual bool isReadyToRender() const;
  virtual void onDimensionChangedEvent();
  virtual void onGameEventNotification(ui::GameEventNotification);
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > getTopScreenName() const;
  virtual void setLeaveGameInProgressAsReadyToContinue();
  virtual void stopDestroying();
  virtual void onClientCreatedLevel(std::pair<std::unique_ptr<Level,std::default_delete<Level> >,OwnerPtrT<EntityRefTraits> >, std::unique_ptr<LocalPlayer,std::default_delete<LocalPlayer> >);
  virtual uint64_t getClientRandomId() const;
  virtual UserAuthentication& getUserAuthentication();
  virtual std::weak_ptr<UserAuthentication> getWeakUserAuthentication();
  virtual void registerToUserManager(const gsl::not_null<Bedrock::NonOwnerPointer<Social::IUserManager> >&, int32_t);
  virtual void resumeWithUserManager(const gsl::not_null<Bedrock::NonOwnerPointer<Social::IUserManager> >&, int32_t);
  virtual void createUserAuthentication(uint64_t, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void createUserAuthentication(std::basic_string<char,std::char_traits<char>,std::allocator<char> >);
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > getPlatformId() const;
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > getPlatformOnlineId() const;
  virtual bool isHoloCursorNeeded() const;
  virtual bool useController() const;
  virtual bool useTouchscreen() const;
  virtual bool getMouseGrabbed() const;
  virtual bool currentInputModeIsGamePadOrMotionController() const;
  virtual bool currentInputModeIsMouseAndKeyboard() const;
  virtual bool getForceMonoscopic() const;
  virtual bool allowPicking() const;
  virtual bool isShowingMenu() const;
  virtual bool isShowingProgressScreen() const;
  virtual bool isShowingWorldProgressScreen() const;
  virtual bool isShowingDeathScreen() const;
  virtual bool isScreenReplaceable() const;
  virtual bool isInGame() const;
  virtual bool isWorldActive() const;
  virtual bool isInRealm();
  virtual bool readyForShutdown() const;
  virtual bool isPrimaryClient() const;
  virtual bool isEduMode() const;
  virtual bool isGamepadCursorEnabled() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<Minecraft const > > getServerData() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<Minecraft> > getServerData();
  virtual const MultiPlayerLevel* getLevel() const;
  virtual MultiPlayerLevel* getLevel();
  virtual bool isPreGame() const;
  virtual bool isInMultiplayerGame() const;
  virtual bool isMultiPlayerClient() const;
  virtual const Options& getOptions() const;
  virtual Options& getOptions();
  virtual const std::shared_ptr<Options const > getOptionsPtr() const;
  virtual std::shared_ptr<Options> getOptionsPtr();
  virtual const std::shared_ptr<Social::User const > getUser() const;
  virtual std::shared_ptr<Social::User> getUser();
  virtual GameRenderer& getGameRenderer() const;
  virtual HolosceneRenderer* getHolosceneRenderer() const;
  virtual LevelRenderer* getLevelRenderer() const;
  virtual LevelRendererCameraProxy* getLevelRendererCameraProxy() const;
  virtual const CameraManager* getCameraManager() const;
  virtual CameraManager* getCameraManager();
  virtual LightTexture* getLightTexture();
  virtual void setupLevelRendering(Level&, Actor&);
  virtual const mce::ViewportInfo& getViewportInfo() const;
  virtual void setViewportInfo(const mce::ViewportInfo&);
  virtual Vec2 getNormalizedViewportSize() const;
  virtual void updateChunkRadius();
  virtual void setUITexture(mce::Texture*);
  virtual mce::Texture* getUITexture();
  virtual void setLevelTexture(mce::Texture*);
  virtual mce::Texture* getLevelTexture();
  virtual void setUICursorTexture(mce::TexturePtr);
  virtual mce::TexturePtr getUICursorTexture() const;
  virtual mce::Camera& getCamera();
  virtual ShaderColor& getShaderColor();
  virtual ShaderColor& getDarkShaderColor();
  virtual void clearGraphicsCache();
  virtual void getNormalizedUICursorTransform(MatrixStack::MatrixStackRef&, float);
  virtual bool shouldRenderUICursor() const;
  virtual bool getRenderPlayerModel() const;
  virtual bool getCameraFacesPlayerFront() const;
  virtual ChunkDisplay* getChunkCacheDisplay() const;
  virtual BiomeMapDisplay* getBiomeMapDisplay() const;
  virtual float getGuiScale() const;
  virtual const Option& getGuiScaleOption() const;
  virtual int32_t getGuiScaleOffset() const;
  virtual void setGuiScaleOffset(int32_t);
  virtual void renderImGui(ScreenContext&, bool);
  virtual const GuiData& getGuiData() const;
  virtual GuiData& getGuiData();
  virtual GuidedFlowManager& getGuidedFlowManager();
  virtual const PixelCalc& getDpadScale() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<DateManager const > > getDateManager() const;
  virtual void addOverrideHoursToDateTime(const uint32_t);
  virtual ToastManager& getToastManager();
  virtual const AbstractScene* getTopScene() const;
  virtual AbstractScene* getTopScene();
  virtual const AbstractScene* getActiveScene() const;
  virtual AbstractScene* getActiveScene();
  virtual SceneFactory& getSceneFactory() const;
  virtual SceneStack& getClientSceneStack();
  virtual const SceneStack& getClientSceneStack() const;
  virtual hbui::Router& getClientUIRouter() const;
  virtual const SceneStack& getMainSceneStack() const;
  virtual SceneStack& getMainSceneStack();
  virtual SceneStack& getCurrentSceneStack();
  virtual const SceneStack& getCurrentSceneStack() const;
  virtual const hbui::Router& getCurrentUIRouter() const;
  virtual hbui::Router& getCurrentUIRouter();
  virtual hbui::ITelemetry& getHBUITelemetry();
  virtual SceneStack& prepareSceneFor(const ui::SceneType, std::function<std::shared_ptr<AbstractScene> __cdecl(void)>);
  virtual CachedScenes& getCachedScenes();
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > getScreenName() const;
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > getScreenTelemetry() const;
  virtual ui::SceneType getTopSceneType() const;
  virtual MobEffectsLayout& getMobEffectsLayout();
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > emoticonifyText(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, bool);
  virtual std::basic_string<char,std::char_traits<char>,std::allocator<char> > emoticonifyText(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&) const;
  virtual void onMobEffectsChange();
  virtual void setUISizeAndScale(int32_t, int32_t, float);
  virtual void forEachVisibleScreen(std::function<void __cdecl(AbstractScene &)>, bool);
  virtual void forEachScreen(std::function<bool __cdecl(AbstractScene &)>, bool);
  virtual void forEachScreenConst(std::function<bool __cdecl(AbstractScene const &)>, bool) const;
  virtual bool updateSceneStack();
  virtual void forEachAlwaysAcceptInputScreen(std::function<void __cdecl(AbstractScene &)>, const AbstractScene*);
  virtual void forEachAlwaysAcceptInputScreenWithTop(std::function<void __cdecl(AbstractScene &)>);
  virtual void showPlayerProfile(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, mce::UUID, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual InputMode getCurrentInputMode() const;
  virtual bool isTouchGameplayAllowed() const;
  virtual Bedrock::NonOwnerPointer<MinecraftInputHandler> getMinecraftInput() const;
  virtual void setHoloInput(std::unique_ptr<HolographicPlatform,std::default_delete<HolographicPlatform> >);
  virtual HolographicPlatform& getHoloInput() const;
  virtual VoiceSystem& getVoiceSystem() const;
  virtual KeyboardManager& getKeyboardManager();
  virtual void setVoiceSystem(std::unique_ptr<VoiceSystem,std::default_delete<VoiceSystem> >);
  virtual void setLastPointerLocation(float, float, float);
  virtual Vec3& getLastPointerLocation();
  virtual bool shouldUseLastPointerLocationOnFocusChange();
  virtual void adjustGazeCursorByMouse(float, float);
  virtual bool currentScreenShouldStealMouse();
  virtual BuildActionIntention& getInProgressBAI() const;
  virtual bool newDictationDataAvailable() const;
  virtual void clearDictationDataAvailable();
  virtual const std::basic_string<char,std::char_traits<char>,std::allocator<char> >& getDictationText() const;
  virtual PacketSender& getPacketSender();
  virtual const NetworkHandler& getClientNetworkSystem() const;
  virtual NetworkHandler& getClientNetworkSystem();
  virtual void setMoveTurnInput(std::unique_ptr<MoveInputHandler,std::default_delete<MoveInputHandler> >);
  virtual MoveInputHandler& getMoveTurnInput();
  virtual void setupPersistentControls(InputMode);
  virtual void resetPlayerMovement();
  virtual void suspendPredictedMovement();
  virtual void onClientInputInitComplete();
  virtual void setClientInputHandler(std::unique_ptr<ClientInputHandler,std::default_delete<ClientInputHandler> >);
  virtual ClientInputHandler* getInput() const;
  virtual int32_t getControllerId() const;
  virtual bool hasConnectedController() const;
  virtual unsigned char getClientSubId() const;
  virtual void setSuspendInput(bool);
  virtual void setDisableInput(bool);
  virtual void grabMouse();
  virtual void releaseMouse();
  virtual void refocusMouse(bool);
  virtual void resetBai(int32_t);
  virtual void clearInProgressBAI();
  virtual gsl::not_null<Bedrock::NonOwnerPointer<SoundEngine> > getSoundEngine() const;
  virtual void play(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const Vec3&, float, float);
  virtual void playUI(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, float, float);
  virtual void muteAudio();
  virtual void unMuteAudio();
  virtual void fadeOutMusic() const;
  virtual TaskGroup& getTaskGroup();
  virtual void onFullVanillaPackOnStack();
  virtual bool isFullVanillaPackOnStack() const;
  virtual void onPlayerLoaded(Player&);
  virtual void setClientGameMode(GameType);
  virtual void resetToDefaultGameMode();
  virtual IGameConnectionListener& getGameConnectionListener();
  virtual void connectToThirdPartyServer(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, int32_t);
  virtual void startExternalNetworkWorld(Social::GameConnectionInfo, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, bool);
  virtual bool checkForPiracy();
  virtual void updateChatFilterStatus();
  virtual void updateControllerHandling();
  virtual void onPlayerDestruction(Player&);
  virtual void setBehaviorCommandCallback(std::function<void __cdecl(std::basic_string<char,std::char_traits<char>,std::allocator<char> > const &,enum BehaviorStatus)>);
  virtual void setBehaviorCommandStatus(std::basic_string<char,std::char_traits<char>,std::allocator<char> >, BehaviorStatus);
  virtual void setConnectGamepadScreenActive(bool);
  virtual Core::PathBuffer<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > requestScreenshot(ScreenshotOptions&);
  virtual DevConsoleLogger& getDevConsoleLogger() const;
  virtual const AbstractClientInstanceTestInterface& getTestInterface() const;
  virtual AbstractClientInstanceTestInterface& getTestInterface();
  virtual std::shared_ptr<FileDataRequest> requestImageFromUrl(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, std::function<void __cdecl(Core::Path const &)>);
  virtual void onExtendDiskSpace(const bool, std::weak_ptr<Core::FileStorageArea>&, const uint64_t&, std::function<void __cdecl(void)>);
  virtual void onLowDiskSpace(const bool);
  virtual void onOutOfDiskSpace(const bool);
  virtual void onCriticalDiskError(const bool, const Core::LevelStorageState&);
  virtual void onLevelCorrupt();
  virtual void onGameModeChanged();
  virtual void onBeforeSimTick();
  virtual void onTick(int32_t, int32_t);
  virtual void onInternetUpdate();
  virtual void onGameSessionReset();
  virtual void onLevelExit();
  virtual void updateScreens();
  virtual void initializeRenderResources();
  virtual void postInitRenderResources();
  virtual void onAppSuspended();
  virtual void onActiveResourcePacksChanged(std::shared_ptr<ActorResourceDefinitionGroup>);
  virtual void reloadEntityRenderers(std::shared_ptr<ActorResourceDefinitionGroup>);
  virtual BlockTessellator& getBlockTessellator();
  virtual BlockActorRenderDispatcher& getBlockEntityRenderDispatcher();
  virtual std::shared_ptr<ActorRenderDispatcher> getEntityRenderDispatcher();
  virtual ActorBlockRenderer& getEntityBlockRenderer();
  virtual ItemInHandRenderer* getItemInHandRenderer();
  virtual ItemRenderer* getItemRenderer();
  virtual std::deque<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >& getSentMessageHistory();
  virtual std::deque<std::basic_string<char,std::char_traits<char>,std::allocator<char> >,std::allocator<std::basic_string<char,std::char_traits<char>,std::allocator<char> > > >& getDevConsoleMessageHistory();
  virtual const UIProfanityContext& getUIProfanityContext() const;
  virtual void initTTSClient(std::shared_ptr<TextToSpeechClient>);
  virtual std::shared_ptr<TextToSpeechClient const > getTTSClient() const;
  virtual std::shared_ptr<TextToSpeechClient> getTTSClient();
  virtual std::shared_ptr<ITTSEventManager> getTTSEventManager();
  virtual void addTTSMessage(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, ProfanityFilterContext, bool, bool, bool);
  virtual void initCommands();
  virtual uint32_t getUserId() const;
  virtual double getServerConnectionTime() const;
  virtual const ClientHMDState& getHMDState() const;
  virtual ClientHMDState& getHMDState();
  virtual void setServerPingTime(int32_t);
  virtual int32_t getServerPingTime() const;
  virtual void setDefaultPlayscreenTab(PlayScreenDefaultTab);
  virtual void setClientInstanceState(const ClientInstanceState&);
  virtual void setUIEventCoordinator(std::unique_ptr<UIEventCoordinator,std::default_delete<UIEventCoordinator> >&);
  virtual gsl::not_null<Bedrock::NonOwnerPointer<UIEventCoordinator> > getUIEventCoordinator();
  virtual void computeScreenCoordsFromScreenNormCoords(float, float, int16_t&, int16_t&);
  virtual std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > > getNoBlockBreakUntil();
  virtual void setNoBlockBreakUntil(std::chrono::time_point<std::chrono::steady_clock,std::chrono::duration<__int64,std::ratio<1,1000000000> > >);
  virtual void setDictation(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  virtual void setNewDictationString(bool);
  virtual GameCallbacks& getGameCallbacks();
  virtual Core::StorageAreaStateListener& getStorageAreaStateListener();
  virtual gsl::not_null<Bedrock::NonOwnerPointer<ClientInstanceEventCoordinator> > getEventCoordinator();
  virtual GameModuleClient* getGameModule();
  ClientHitDetectCoordinator& getHitEventCoordinator();
  virtual MinecraftClientScriptEngine* getScriptEngine();
  virtual void sendClientEnteredLevel();
  virtual HitDetectSystem* getHitDetectSystem();
  virtual bool isPlaying() const;
  virtual ClientInstanceState getClientInstanceState() const;
  virtual LatencyGraphDisplay* getLatencyGraphDisplay() const;
  virtual const PlayerCapabilities::IClientController& getClientCapabilities() const;
  virtual std::weak_ptr<IClientInstance> getWeakPtrToThis();
  virtual const ClientRequirementVerifier& getClientRequirementVerifier() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<FogDefinitionRegistry> > getFogDefinitionRegistry();
  virtual gsl::not_null<Bedrock::NonOwnerPointer<FogDefinitionRegistry const > > getFogDefinitionRegistry() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<FogManager> > getFogManager();
  virtual gsl::not_null<Bedrock::NonOwnerPointer<FogManager const > > getFogManager() const;
  virtual gsl::not_null<Bedrock::NonOwnerPointer<ScreenLoadTimeTracker> > getScreenLoadTimeTracker();
  void _startExternalNetworkWorld(Social::GameConnectionInfo, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  void _createSkinRepositoryClientInterface();
  void _fetchStoreItemByProductId(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, StoreCatalogItemType);
  void _fetchItemAndNavigateToPurchaseScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const bool);
  void _processNewGazeHoloScreenData();
  void _initSceneStack();
  bool _getSceneStackChangedThisFrame() const;
  void _navigateToDisconnectScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, bool);
  void _navigateToStoreHomeScreen(SceneStack&, SceneFactory&);
  void _getViewPortModifiers(Vec2&, Vec2&) const;
  int32_t _calculateMaxGuiScaleIndex(const Vec2&) const;
  int32_t _calculateGuiScaleIndex(const Vec2&, int32_t) const;
  void _updateScreenSizeVariables(const Vec2&, float, float, float);
  void _onScreenSizeVariablesChanged(const ScreenSizeData&);
  void _loadProfanityFilter();
  bool _needsAsyncLateJoin() const;
  void _joinWorldInProgress();
  bool _isShowingScreen(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&) const;
  void _startWorldSubClient(std::unique_ptr<Certificate,std::default_delete<Certificate> >);
  void _startWorldPrimaryClient(std::unique_ptr<Certificate,std::default_delete<Certificate> >);
  std::unique_ptr<LegacyClientNetworkHandler,std::default_delete<LegacyClientNetworkHandler> > _createNetworkHandler(std::unique_ptr<Certificate,std::default_delete<Certificate> >);
  void _removeSubclient();
  void _requestLeaveGameImpl(const bool, const bool);
  void _startLeaveGame();
  void _startDestroyingGame();
  bool _continueDestroyingGame();
  void _finishDestroyingGame();
  void _tickBuildAction(const HitResult&, const HitResult&, bool);
  CrashDumpLogStringID _getCrashDumpLogCategory();
  void _leaveGameOnUnrecoverableError(const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&, const std::basic_string<char,std::char_traits<char>,std::allocator<char> >&);
  void _garbageCollectRenderChunkCoordinator();
  void __autoclassinit2(uint64_t);
  virtual void* __vecDelDtor(uint32_t);
  
  static bool tickDestroyBlock(ClientInstance::ClientDestroyBlockState&, bool);
  static cg::math::Rect<float> getViewPortModifiers(const unsigned char, const uint64_t, const SplitScreenDirection);
};
